/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'superAdmin' : null } |
  { 'treasurer' : null } |
  { 'smpAdmin' : null } |
  { 'smaAdmin' : null };
export interface CreatePaymentRequest {
  'id' : bigint,
  'receiptImage' : ExternalBlob,
  'paymentMethod' : PaymentMethod,
  'date' : bigint,
  'studentNis' : string,
  'institutionId' : bigint,
  'notes' : string,
  'brand' : string,
  'amount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Institution {
  'id' : bigint,
  'name' : string,
  'address' : string,
}
export interface Payment {
  'id' : bigint,
  'receiptImage' : ExternalBlob,
  'paymentMethod' : PaymentMethod,
  'date' : bigint,
  'institution' : Institution,
  'createdAt' : bigint,
  'studentNis' : string,
  'notes' : string,
  'brand' : string,
  'amount' : bigint,
}
export type PaymentMethod = { 'cash' : null } |
  { 'transfer' : null };
export interface SppSetting {
  'id' : bigint,
  'receiptImage' : ExternalBlob,
  'paymentMethod' : PaymentMethod,
  'date' : bigint,
  'institution' : Institution,
  'createdAt' : bigint,
  'notes' : string,
  'brand' : string,
  'amount' : bigint,
}
export type StatusSantri = { 'bersekolah' : null } |
  { 'lulus' : null };
export interface Student {
  'nis' : string,
  'status' : StatusSantri,
  'classNumber' : bigint,
  'institution' : Institution,
  'fullName' : string,
  'guardianPhone' : string,
  'noInduk' : string,
  'enrollmentDate' : bigint,
  'guardianName' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : AppRole,
  'institutionId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInstitution' : ActorMethod<[string, string], Institution>,
  'addStudent' : ActorMethod<
    [string, bigint, string, string, bigint, string, string, bigint],
    Student
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPayment' : ActorMethod<[CreatePaymentRequest], Payment>,
  'createSppSetting' : ActorMethod<
    [bigint, string, bigint, PaymentMethod, ExternalBlob, string, bigint],
    SppSetting
  >,
  'deletePayment' : ActorMethod<[bigint], undefined>,
  'deleteSppSetting' : ActorMethod<[bigint], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalSmpStudents' : bigint,
      'totalArrearsThisMonth' : bigint,
      'totalSmaStudents' : bigint,
      'totalPaymentsThisMonth' : bigint,
    }
  >,
  'getInstitution' : ActorMethod<[bigint], [] | [Institution]>,
  'getPayment' : ActorMethod<[bigint], [] | [Payment]>,
  'getSppSetting' : ActorMethod<[bigint], [] | [SppSetting]>,
  'getStudent' : ActorMethod<[string], [] | [Student]>,
  'getStudentPaymentHistory' : ActorMethod<[string], Array<Payment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listInstitutions' : ActorMethod<[], Array<Institution>>,
  'listPayments' : ActorMethod<[[] | [bigint], [] | [string]], Array<Payment>>,
  'listSppSettings' : ActorMethod<[[] | [bigint]], Array<SppSetting>>,
  'listStudents' : ActorMethod<
    [[] | [bigint], [] | [StatusSantri]],
    Array<Student>
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePayment' : ActorMethod<
    [bigint, bigint, bigint, PaymentMethod, string],
    Payment
  >,
  'updateSppSetting' : ActorMethod<
    [bigint, bigint, string, string],
    SppSetting
  >,
  'updateStudent' : ActorMethod<
    [string, bigint, string, string, string],
    Student
  >,
  'updateStudentStatus' : ActorMethod<[string, StatusSantri], Student>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];