/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Institution = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const StatusSantri = IDL.Variant({
  'bersekolah' : IDL.Null,
  'lulus' : IDL.Null,
});
export const Student = IDL.Record({
  'nis' : IDL.Text,
  'status' : StatusSantri,
  'classNumber' : IDL.Nat,
  'institution' : Institution,
  'fullName' : IDL.Text,
  'guardianPhone' : IDL.Text,
  'noInduk' : IDL.Text,
  'enrollmentDate' : IDL.Int,
  'guardianName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'transfer' : IDL.Null,
});
export const CreatePaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'receiptImage' : ExternalBlob,
  'paymentMethod' : PaymentMethod,
  'date' : IDL.Int,
  'studentNis' : IDL.Text,
  'institutionId' : IDL.Nat,
  'notes' : IDL.Text,
  'brand' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'receiptImage' : ExternalBlob,
  'paymentMethod' : PaymentMethod,
  'date' : IDL.Int,
  'institution' : Institution,
  'createdAt' : IDL.Int,
  'studentNis' : IDL.Text,
  'notes' : IDL.Text,
  'brand' : IDL.Text,
  'amount' : IDL.Nat,
});
export const SppSetting = IDL.Record({
  'id' : IDL.Nat,
  'receiptImage' : ExternalBlob,
  'paymentMethod' : PaymentMethod,
  'date' : IDL.Int,
  'institution' : Institution,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'brand' : IDL.Text,
  'amount' : IDL.Nat,
});
export const AppRole = IDL.Variant({
  'superAdmin' : IDL.Null,
  'treasurer' : IDL.Null,
  'smpAdmin' : IDL.Null,
  'smaAdmin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : AppRole,
  'institutionId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInstitution' : IDL.Func([IDL.Text, IDL.Text], [Institution], []),
  'addStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [Student],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPayment' : IDL.Func([CreatePaymentRequest], [Payment], []),
  'createSppSetting' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Int,
        PaymentMethod,
        ExternalBlob,
        IDL.Text,
        IDL.Nat,
      ],
      [SppSetting],
      [],
    ),
  'deletePayment' : IDL.Func([IDL.Nat], [], []),
  'deleteSppSetting' : IDL.Func([IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalSmpStudents' : IDL.Nat,
          'totalArrearsThisMonth' : IDL.Nat,
          'totalSmaStudents' : IDL.Nat,
          'totalPaymentsThisMonth' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getInstitution' : IDL.Func([IDL.Nat], [IDL.Opt(Institution)], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'getSppSetting' : IDL.Func([IDL.Nat], [IDL.Opt(SppSetting)], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getStudentPaymentHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listInstitutions' : IDL.Func([], [IDL.Vec(Institution)], ['query']),
  'listPayments' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'listSppSettings' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(SppSetting)],
      ['query'],
    ),
  'listStudents' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(StatusSantri)],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Int, PaymentMethod, IDL.Text],
      [Payment],
      [],
    ),
  'updateSppSetting' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [SppSetting],
      [],
    ),
  'updateStudent' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Student],
      [],
    ),
  'updateStudentStatus' : IDL.Func([IDL.Text, StatusSantri], [Student], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Institution = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const StatusSantri = IDL.Variant({
    'bersekolah' : IDL.Null,
    'lulus' : IDL.Null,
  });
  const Student = IDL.Record({
    'nis' : IDL.Text,
    'status' : StatusSantri,
    'classNumber' : IDL.Nat,
    'institution' : Institution,
    'fullName' : IDL.Text,
    'guardianPhone' : IDL.Text,
    'noInduk' : IDL.Text,
    'enrollmentDate' : IDL.Int,
    'guardianName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const CreatePaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'receiptImage' : ExternalBlob,
    'paymentMethod' : PaymentMethod,
    'date' : IDL.Int,
    'studentNis' : IDL.Text,
    'institutionId' : IDL.Nat,
    'notes' : IDL.Text,
    'brand' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'receiptImage' : ExternalBlob,
    'paymentMethod' : PaymentMethod,
    'date' : IDL.Int,
    'institution' : Institution,
    'createdAt' : IDL.Int,
    'studentNis' : IDL.Text,
    'notes' : IDL.Text,
    'brand' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const SppSetting = IDL.Record({
    'id' : IDL.Nat,
    'receiptImage' : ExternalBlob,
    'paymentMethod' : PaymentMethod,
    'date' : IDL.Int,
    'institution' : Institution,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'brand' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const AppRole = IDL.Variant({
    'superAdmin' : IDL.Null,
    'treasurer' : IDL.Null,
    'smpAdmin' : IDL.Null,
    'smaAdmin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : AppRole,
    'institutionId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInstitution' : IDL.Func([IDL.Text, IDL.Text], [Institution], []),
    'addStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [Student],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPayment' : IDL.Func([CreatePaymentRequest], [Payment], []),
    'createSppSetting' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Int,
          PaymentMethod,
          ExternalBlob,
          IDL.Text,
          IDL.Nat,
        ],
        [SppSetting],
        [],
      ),
    'deletePayment' : IDL.Func([IDL.Nat], [], []),
    'deleteSppSetting' : IDL.Func([IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalSmpStudents' : IDL.Nat,
            'totalArrearsThisMonth' : IDL.Nat,
            'totalSmaStudents' : IDL.Nat,
            'totalPaymentsThisMonth' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getInstitution' : IDL.Func([IDL.Nat], [IDL.Opt(Institution)], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
    'getSppSetting' : IDL.Func([IDL.Nat], [IDL.Opt(SppSetting)], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getStudentPaymentHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listInstitutions' : IDL.Func([], [IDL.Vec(Institution)], ['query']),
    'listPayments' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'listSppSettings' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(SppSetting)],
        ['query'],
      ),
    'listStudents' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(StatusSantri)],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Int, PaymentMethod, IDL.Text],
        [Payment],
        [],
      ),
    'updateSppSetting' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [SppSetting],
        [],
      ),
    'updateStudent' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Student],
        [],
      ),
    'updateStudentStatus' : IDL.Func([IDL.Text, StatusSantri], [Student], []),
  });
};

export const init = ({ IDL }) => { return []; };