/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Student {
    nis: string;
    status: StatusSantri;
    classNumber: bigint;
    institution: Institution;
    fullName: string;
    guardianPhone: string;
    noInduk: string;
    enrollmentDate: bigint;
    guardianName: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CreatePaymentRequest {
    id: bigint;
    receiptImage: ExternalBlob;
    paymentMethod: PaymentMethod;
    date: bigint;
    studentNis: string;
    institutionId: bigint;
    notes: string;
    brand: string;
    amount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Payment {
    id: bigint;
    receiptImage: ExternalBlob;
    paymentMethod: PaymentMethod;
    date: bigint;
    institution: Institution;
    createdAt: bigint;
    studentNis: string;
    notes: string;
    brand: string;
    amount: bigint;
}
export interface SppSetting {
    id: bigint;
    receiptImage: ExternalBlob;
    paymentMethod: PaymentMethod;
    date: bigint;
    institution: Institution;
    createdAt: bigint;
    notes: string;
    brand: string;
    amount: bigint;
}
export interface Institution {
    id: bigint;
    name: string;
    address: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    role: AppRole;
    institutionId?: bigint;
}
export enum AppRole {
    superAdmin = "superAdmin",
    treasurer = "treasurer",
    smpAdmin = "smpAdmin",
    smaAdmin = "smaAdmin"
}
export enum PaymentMethod {
    cash = "cash",
    transfer = "transfer"
}
export enum StatusSantri {
    bersekolah = "bersekolah",
    lulus = "lulus"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInstitution(name: string, address: string): Promise<Institution>;
    addStudent(nis: string, classNumber: bigint, noInduk: string, fullName: string, instId: bigint, guardianName: string, guardianPhone: string, enrollmentDate: bigint): Promise<Student>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPayment(request: CreatePaymentRequest): Promise<Payment>;
    createSppSetting(amount: bigint, brand: string, date: bigint, paymentMethod: PaymentMethod, receiptImage: ExternalBlob, notes: string, institutionId: bigint): Promise<SppSetting>;
    deletePayment(paymentId: bigint): Promise<void>;
    deleteSppSetting(id: bigint): Promise<void>;
    deleteStudent(nis: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        totalSmpStudents: bigint;
        totalArrearsThisMonth: bigint;
        totalSmaStudents: bigint;
        totalPaymentsThisMonth: bigint;
    }>;
    getInstitution(id: bigint): Promise<Institution | null>;
    getPayment(id: bigint): Promise<Payment | null>;
    getSppSetting(id: bigint): Promise<SppSetting | null>;
    getStudent(nis: string): Promise<Student | null>;
    getStudentPaymentHistory(studentNis: string): Promise<Array<Payment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listInstitutions(): Promise<Array<Institution>>;
    listPayments(institutionId: bigint | null, studentNis: string | null): Promise<Array<Payment>>;
    listSppSettings(institutionId: bigint | null): Promise<Array<SppSetting>>;
    listStudents(institutionId: bigint | null, status: StatusSantri | null): Promise<Array<Student>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePayment(id: bigint, amount: bigint, date: bigint, paymentMethod: PaymentMethod, notes: string): Promise<Payment>;
    updateSppSetting(id: bigint, amount: bigint, brand: string, notes: string): Promise<SppSetting>;
    updateStudent(nis: string, classNumber: bigint, fullName: string, guardianName: string, guardianPhone: string): Promise<Student>;
    updateStudentStatus(nis: string, status: StatusSantri): Promise<Student>;
}
import type { AppRole as _AppRole, CreatePaymentRequest as _CreatePaymentRequest, ExternalBlob as _ExternalBlob, Institution as _Institution, Payment as _Payment, PaymentMethod as _PaymentMethod, SppSetting as _SppSetting, StatusSantri as _StatusSantri, Student as _Student, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInstitution(arg0: string, arg1: string): Promise<Institution> {
        if (this.processError) {
            try {
                const result = await this.actor.addInstitution(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInstitution(arg0, arg1);
            return result;
        }
    }
    async addStudent(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: bigint): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_Student_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_Student_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPayment(arg0: CreatePaymentRequest): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(await to_candid_CreatePaymentRequest_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Payment_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(await to_candid_CreatePaymentRequest_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Payment_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSppSetting(arg0: bigint, arg1: string, arg2: bigint, arg3: PaymentMethod, arg4: ExternalBlob, arg5: string, arg6: bigint): Promise<SppSetting> {
        if (this.processError) {
            try {
                const result = await this.actor.createSppSetting(arg0, arg1, arg2, to_candid_PaymentMethod_n17(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return from_candid_SppSetting_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSppSetting(arg0, arg1, arg2, to_candid_PaymentMethod_n17(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return from_candid_SppSetting_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async deleteSppSetting(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSppSetting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSppSetting(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        totalSmpStudents: bigint;
        totalArrearsThisMonth: bigint;
        totalSmaStudents: bigint;
        totalPaymentsThisMonth: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getInstitution(arg0: bigint): Promise<Institution | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstitution(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstitution(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: bigint): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSppSetting(arg0: bigint): Promise<SppSetting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSppSetting(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSppSetting(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: string): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentPaymentHistory(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentPaymentHistory(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentPaymentHistory(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listInstitutions(): Promise<Array<Institution>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInstitutions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInstitutions();
            return result;
        }
    }
    async listPayments(arg0: bigint | null, arg1: string | null): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayments(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayments(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSppSettings(arg0: bigint | null): Promise<Array<SppSetting>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSppSettings(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSppSettings(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(arg0: bigint | null, arg1: StatusSantri | null): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePayment(arg0: bigint, arg1: bigint, arg2: bigint, arg3: PaymentMethod, arg4: string): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, arg1, arg2, to_candid_PaymentMethod_n17(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Payment_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, arg1, arg2, to_candid_PaymentMethod_n17(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Payment_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSppSetting(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<SppSetting> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSppSetting(arg0, arg1, arg2, arg3);
                return from_candid_SppSetting_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSppSetting(arg0, arg1, arg2, arg3);
            return from_candid_SppSetting_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudent(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Student_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Student_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudentStatus(arg0: string, arg1: StatusSantri): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentStatus(arg0, to_candid_StatusSantri_n42(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Student_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentStatus(arg0, to_candid_StatusSantri_n42(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Student_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PaymentMethod_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Payment_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Promise<Payment> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_SppSetting_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SppSetting): Promise<SppSetting> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_StatusSantri_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusSantri): StatusSantri {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Institution]): Institution | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Promise<Payment | null> {
    return value.length === 0 ? null : await from_candid_Payment_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SppSetting]): Promise<SppSetting | null> {
    return value.length === 0 ? null : await from_candid_SppSetting_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    receiptImage: _ExternalBlob;
    paymentMethod: _PaymentMethod;
    date: bigint;
    institution: _Institution;
    createdAt: bigint;
    studentNis: string;
    notes: string;
    brand: string;
    amount: bigint;
}): Promise<{
    id: bigint;
    receiptImage: ExternalBlob;
    paymentMethod: PaymentMethod;
    date: bigint;
    institution: Institution;
    createdAt: bigint;
    studentNis: string;
    notes: string;
    brand: string;
    amount: bigint;
}> {
    return {
        id: value.id,
        receiptImage: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.receiptImage),
        paymentMethod: from_candid_PaymentMethod_n22(_uploadFile, _downloadFile, value.paymentMethod),
        date: value.date,
        institution: value.institution,
        createdAt: value.createdAt,
        studentNis: value.studentNis,
        notes: value.notes,
        brand: value.brand,
        amount: value.amount
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    receiptImage: _ExternalBlob;
    paymentMethod: _PaymentMethod;
    date: bigint;
    institution: _Institution;
    createdAt: bigint;
    notes: string;
    brand: string;
    amount: bigint;
}): Promise<{
    id: bigint;
    receiptImage: ExternalBlob;
    paymentMethod: PaymentMethod;
    date: bigint;
    institution: Institution;
    createdAt: bigint;
    notes: string;
    brand: string;
    amount: bigint;
}> {
    return {
        id: value.id,
        receiptImage: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.receiptImage),
        paymentMethod: from_candid_PaymentMethod_n22(_uploadFile, _downloadFile, value.paymentMethod),
        date: value.date,
        institution: value.institution,
        createdAt: value.createdAt,
        notes: value.notes,
        brand: value.brand,
        amount: value.amount
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _AppRole;
    institutionId: [] | [bigint];
}): {
    name: string;
    role: AppRole;
    institutionId?: bigint;
} {
    return {
        name: value.name,
        role: from_candid_AppRole_n29(_uploadFile, _downloadFile, value.role),
        institutionId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.institutionId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nis: string;
    status: _StatusSantri;
    classNumber: bigint;
    institution: _Institution;
    fullName: string;
    guardianPhone: string;
    noInduk: string;
    enrollmentDate: bigint;
    guardianName: string;
}): {
    nis: string;
    status: StatusSantri;
    classNumber: bigint;
    institution: Institution;
    fullName: string;
    guardianPhone: string;
    noInduk: string;
    enrollmentDate: bigint;
    guardianName: string;
} {
    return {
        nis: value.nis,
        status: from_candid_StatusSantri_n10(_uploadFile, _downloadFile, value.status),
        classNumber: value.classNumber,
        institution: value.institution,
        fullName: value.fullName,
        guardianPhone: value.guardianPhone,
        noInduk: value.noInduk,
        enrollmentDate: value.enrollmentDate,
        guardianName: value.guardianName
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bersekolah: null;
} | {
    lulus: null;
}): StatusSantri {
    return "bersekolah" in value ? StatusSantri.bersekolah : "lulus" in value ? StatusSantri.lulus : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    transfer: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "transfer" in value ? PaymentMethod.transfer : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    superAdmin: null;
} | {
    treasurer: null;
} | {
    smpAdmin: null;
} | {
    smaAdmin: null;
}): AppRole {
    return "superAdmin" in value ? AppRole.superAdmin : "treasurer" in value ? AppRole.treasurer : "smpAdmin" in value ? AppRole.smpAdmin : "smaAdmin" in value ? AppRole.smaAdmin : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Promise<Array<Payment>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Payment_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SppSetting>): Promise<Array<SppSetting>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SppSetting_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
async function to_candid_CreatePaymentRequest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePaymentRequest): Promise<_CreatePaymentRequest> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PaymentMethod_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_StatusSantri_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusSantri): _StatusSantri {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusSantri | null): [] | [_StatusSantri] {
    return value === null ? candid_none() : candid_some(to_candid_StatusSantri_n42(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    receiptImage: ExternalBlob;
    paymentMethod: PaymentMethod;
    date: bigint;
    studentNis: string;
    institutionId: bigint;
    notes: string;
    brand: string;
    amount: bigint;
}): Promise<{
    id: bigint;
    receiptImage: _ExternalBlob;
    paymentMethod: _PaymentMethod;
    date: bigint;
    studentNis: string;
    institutionId: bigint;
    notes: string;
    brand: string;
    amount: bigint;
}> {
    return {
        id: value.id,
        receiptImage: await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.receiptImage),
        paymentMethod: to_candid_PaymentMethod_n17(_uploadFile, _downloadFile, value.paymentMethod),
        date: value.date,
        studentNis: value.studentNis,
        institutionId: value.institutionId,
        notes: value.notes,
        brand: value.brand,
        amount: value.amount
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: AppRole;
    institutionId?: bigint;
}): {
    name: string;
    role: _AppRole;
    institutionId: [] | [bigint];
} {
    return {
        name: value.name,
        role: to_candid_AppRole_n47(_uploadFile, _downloadFile, value.role),
        institutionId: value.institutionId ? candid_some(value.institutionId) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    transfer: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.transfer ? {
        transfer: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusSantri): {
    bersekolah: null;
} | {
    lulus: null;
} {
    return value == StatusSantri.bersekolah ? {
        bersekolah: null
    } : value == StatusSantri.lulus ? {
        lulus: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    superAdmin: null;
} | {
    treasurer: null;
} | {
    smpAdmin: null;
} | {
    smaAdmin: null;
} {
    return value == AppRole.superAdmin ? {
        superAdmin: null
    } : value == AppRole.treasurer ? {
        treasurer: null
    } : value == AppRole.smpAdmin ? {
        smpAdmin: null
    } : value == AppRole.smaAdmin ? {
        smaAdmin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
